enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v2.225.0-dev.1"
integrations-version = "v0.152.0-dev.1"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Reddit ReVanced"
build-mode = "both"
